name: CI with Anaconda
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['pypy-3.7', 'pypy-3.8']
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment-dev.yml
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest
